Repository Team-TdotMo/T.Mo_Front, pull requests merged in 2022-11, with the labels that each got.

#2 🔀 :: 프로젝트 세팅
  .gitignore
  package-lock.json
  package.json
  public/favicon.ico
  public/index.html
  public/manifest.json
  public/robots.txt
  src/App.css
  src/App.tsx
  src/assets/imgs/arrow.svg
  src/assets/imgs/logo.png
  src/assets/index.ts
  src/components/Open/index.tsx
  src/components/Open/styles.ts
  src/index.css
  src/index.tsx
  src/interface/index.ts
  src/pages/OpenPage/index.tsx
  src/react-app-env.d.ts
  src/reportWebVitals.ts
  src/setupTests.ts
  src/styles/index.ts
  src/utils/Token/index.ts
  tsconfig.json
Labels: 프로젝트 시작

#3 💄 :: OpenPage UI 수정
  src/components/Open/styles.ts
Labels: 수정

#4 💄:: OpenPage UI 수정
  src/components/Open/index.tsx
  src/components/Open/styles2.ts
Labels: 수정

#7 💄:: OpenPage UI 수정
  src/components/Open/styles.ts
Labels: 수정

#12 11 404 Page UI
  src/App.tsx
  src/components/Header/index.tsx
  src/pages/NotFoundPage/index.tsx
Labels: 수정, UI

#14 💄 :: ApplicationList UI 추가
  src/App.tsx
  src/components/ApplicationList/index.tsx
  src/components/ApplicationList/styles.ts
  src/pages/ApplicationListPage/index.tsx
  src/styles/index.ts
Labels: UI

#18 💄:: Modal UI 생성
  src/components/Modal/index.tsx
  src/components/Modal/modal.tsx
Labels: UI
